version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/bridge"
    schedule:
      interval: "weekly"
